name: Update Parent's Submodule

on:
  push:
    branches:
      - main

jobs:
  update-parent-module:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          repository: 'MPZinke/SmartCurtain'
          token: '${{ secrets.SMARTCURTAIN_RW_TOKEN }}'
          submodules: 'true'

      - name: "Update Parent"
        run: |
          git submodule update --remote
          git config --global user.email "mathew.zinke@gmail.com"
          git config --global user.name "mpzinke"
          git commit -am "Updates to track HEAD of SmartCurtain-Frontend"
          git push
